### ISSUE TITLE
Gurobi

### ISSUE THREAD

**Issue by Bungehurst** [fishmarch/SLAM_Map_Compression#1]
Very useful tool! I tried to apply for a Gurobi edu license but I failed, so I used Google Optimization Tools to realize a mix-integer programming solver instead. Here is the code: [SLAM-Map-Compression-OR-Tools](https://github.com/Bungehurst/SLAM-Map-Compression-OR-Tools).

**Comment by fishmarch** [comment]
Thanks for your interest and contribution. I will add a reference to your repo.
